language: scala
scala:
   - 2.11.8
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - shawndgarner@gmail.com
    on_success: change
    on_failure: change
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2